// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.alibaba.dubbo.performance.demo.agent.netty.model.proto;

public interface ProtoBufResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoBufResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestId = 1;</code>
   */
  int getRequestId();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
