// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.alibaba.dubbo.performance.demo.agent.netty.model.proto;

/**
 * Protobuf type {@code ProtoBufRequest}
 */
public  final class ProtoBufRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoBufRequest)
    ProtoBufRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoBufRequest.newBuilder() to construct.
  private ProtoBufRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoBufRequest() {
    requestId_ = 0;
    method_ = "";
    interface_ = "";
    parameterTypesString_ = "";
    parameter_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoBufRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            requestId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            method_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            interface_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            parameterTypesString_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            parameter_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoMessage.internal_static_ProtoBufRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoMessage.internal_static_ProtoBufRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.class, com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.Builder.class);
  }

  public static final int REQUESTID_FIELD_NUMBER = 1;
  private int requestId_;
  /**
   * <code>int32 requestId = 1;</code>
   */
  public int getRequestId() {
    return requestId_;
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  private volatile java.lang.Object method_;
  /**
   * <code>string method = 2;</code>
   */
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERFACE_FIELD_NUMBER = 3;
  private volatile java.lang.Object interface_;
  /**
   * <code>string interface = 3;</code>
   */
  public java.lang.String getInterface() {
    java.lang.Object ref = interface_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interface_ = s;
      return s;
    }
  }
  /**
   * <code>string interface = 3;</code>
   */
  public com.google.protobuf.ByteString
      getInterfaceBytes() {
    java.lang.Object ref = interface_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETERTYPESSTRING_FIELD_NUMBER = 4;
  private volatile java.lang.Object parameterTypesString_;
  /**
   * <code>string parameterTypesString = 4;</code>
   */
  public java.lang.String getParameterTypesString() {
    java.lang.Object ref = parameterTypesString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parameterTypesString_ = s;
      return s;
    }
  }
  /**
   * <code>string parameterTypesString = 4;</code>
   */
  public com.google.protobuf.ByteString
      getParameterTypesStringBytes() {
    java.lang.Object ref = parameterTypesString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parameterTypesString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETER_FIELD_NUMBER = 5;
  private volatile java.lang.Object parameter_;
  /**
   * <code>string parameter = 5;</code>
   */
  public java.lang.String getParameter() {
    java.lang.Object ref = parameter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parameter_ = s;
      return s;
    }
  }
  /**
   * <code>string parameter = 5;</code>
   */
  public com.google.protobuf.ByteString
      getParameterBytes() {
    java.lang.Object ref = parameter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parameter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0) {
      output.writeInt32(1, requestId_);
    }
    if (!getMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
    }
    if (!getInterfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interface_);
    }
    if (!getParameterTypesStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameterTypesString_);
    }
    if (!getParameterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parameter_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, requestId_);
    }
    if (!getMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
    }
    if (!getInterfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, interface_);
    }
    if (!getParameterTypesStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parameterTypesString_);
    }
    if (!getParameterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parameter_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest)) {
      return super.equals(obj);
    }
    com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest other = (com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest) obj;

    boolean result = true;
    result = result && (getRequestId()
        == other.getRequestId());
    result = result && getMethod()
        .equals(other.getMethod());
    result = result && getInterface()
        .equals(other.getInterface());
    result = result && getParameterTypesString()
        .equals(other.getParameterTypesString());
    result = result && getParameter()
        .equals(other.getParameter());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + INTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + getInterface().hashCode();
    hash = (37 * hash) + PARAMETERTYPESSTRING_FIELD_NUMBER;
    hash = (53 * hash) + getParameterTypesString().hashCode();
    hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
    hash = (53 * hash) + getParameter().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProtoBufRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoBufRequest)
      com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoMessage.internal_static_ProtoBufRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoMessage.internal_static_ProtoBufRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.class, com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.Builder.class);
    }

    // Construct using com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      requestId_ = 0;

      method_ = "";

      interface_ = "";

      parameterTypesString_ = "";

      parameter_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoMessage.internal_static_ProtoBufRequest_descriptor;
    }

    public com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest getDefaultInstanceForType() {
      return com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.getDefaultInstance();
    }

    public com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest build() {
      com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest buildPartial() {
      com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest result = new com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest(this);
      result.requestId_ = requestId_;
      result.method_ = method_;
      result.interface_ = interface_;
      result.parameterTypesString_ = parameterTypesString_;
      result.parameter_ = parameter_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest) {
        return mergeFrom((com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest other) {
      if (other == com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest.getDefaultInstance()) return this;
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        onChanged();
      }
      if (!other.getInterface().isEmpty()) {
        interface_ = other.interface_;
        onChanged();
      }
      if (!other.getParameterTypesString().isEmpty()) {
        parameterTypesString_ = other.parameterTypesString_;
        onChanged();
      }
      if (!other.getParameter().isEmpty()) {
        parameter_ = other.parameter_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int requestId_ ;
    /**
     * <code>int32 requestId = 1;</code>
     */
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 requestId = 1;</code>
     */
    public Builder setRequestId(int value) {
      
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 requestId = 1;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     */
    public Builder setMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     */
    public Builder clearMethod() {
      
      method_ = getDefaultInstance().getMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      method_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object interface_ = "";
    /**
     * <code>string interface = 3;</code>
     */
    public java.lang.String getInterface() {
      java.lang.Object ref = interface_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interface_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interface = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceBytes() {
      java.lang.Object ref = interface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interface = 3;</code>
     */
    public Builder setInterface(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interface = 3;</code>
     */
    public Builder clearInterface() {
      
      interface_ = getDefaultInstance().getInterface();
      onChanged();
      return this;
    }
    /**
     * <code>string interface = 3;</code>
     */
    public Builder setInterfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interface_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object parameterTypesString_ = "";
    /**
     * <code>string parameterTypesString = 4;</code>
     */
    public java.lang.String getParameterTypesString() {
      java.lang.Object ref = parameterTypesString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parameterTypesString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parameterTypesString = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParameterTypesStringBytes() {
      java.lang.Object ref = parameterTypesString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parameterTypesString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parameterTypesString = 4;</code>
     */
    public Builder setParameterTypesString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parameterTypesString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string parameterTypesString = 4;</code>
     */
    public Builder clearParameterTypesString() {
      
      parameterTypesString_ = getDefaultInstance().getParameterTypesString();
      onChanged();
      return this;
    }
    /**
     * <code>string parameterTypesString = 4;</code>
     */
    public Builder setParameterTypesStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parameterTypesString_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object parameter_ = "";
    /**
     * <code>string parameter = 5;</code>
     */
    public java.lang.String getParameter() {
      java.lang.Object ref = parameter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parameter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parameter = 5;</code>
     */
    public com.google.protobuf.ByteString
        getParameterBytes() {
      java.lang.Object ref = parameter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parameter = 5;</code>
     */
    public Builder setParameter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string parameter = 5;</code>
     */
    public Builder clearParameter() {
      
      parameter_ = getDefaultInstance().getParameter();
      onChanged();
      return this;
    }
    /**
     * <code>string parameter = 5;</code>
     */
    public Builder setParameterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parameter_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProtoBufRequest)
  }

  // @@protoc_insertion_point(class_scope:ProtoBufRequest)
  private static final com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest();
  }

  public static com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoBufRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProtoBufRequest>() {
    public ProtoBufRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoBufRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoBufRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoBufRequest> getParserForType() {
    return PARSER;
  }

  public com.alibaba.dubbo.performance.demo.agent.netty.model.proto.ProtoBufRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

