// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.alibaba.dubbo.performance.demo.agent.netty.model.proto;

public interface ProtoBufRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoBufRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestId = 1;</code>
   */
  int getRequestId();

  /**
   * <code>string method = 2;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string interface = 3;</code>
   */
  java.lang.String getInterface();
  /**
   * <code>string interface = 3;</code>
   */
  com.google.protobuf.ByteString
      getInterfaceBytes();

  /**
   * <code>string parameterTypesString = 4;</code>
   */
  java.lang.String getParameterTypesString();
  /**
   * <code>string parameterTypesString = 4;</code>
   */
  com.google.protobuf.ByteString
      getParameterTypesStringBytes();

  /**
   * <code>string parameter = 5;</code>
   */
  java.lang.String getParameter();
  /**
   * <code>string parameter = 5;</code>
   */
  com.google.protobuf.ByteString
      getParameterBytes();
}
